# Generated by Django 6.0.7 on 2026-07-11 05:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendance_check_out_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-check_in_time']},
        ),
        migrations.AlterModelOptions(
            name='gym',
            options={'ordering': ['gym_name']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['duration_months']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.gym'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.member'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gym_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.gym'),
        ),
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.membershipplan'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_months',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.gym'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['gym', 'date'], name='core_attend_gym_id_117a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['member', 'date'], name='core_attend_member__15e27b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gym', 'name'], name='core_member_gym_id_456482_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gym', 'phone'], name='core_member_gym_id_e9f0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gym', 'expiry_date'], name='core_member_gym_id_ff9afa_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gym', 'is_active'], name='core_member_gym_id_efca5f_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipplan',
            index=models.Index(fields=['gym', 'plan_name'], name='core_member_gym_id_afc339_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('gym', 'member', 'date'), name='unique_daily_attendance'),
        ),
    ]
