# Generated by Django 6.0.7 on 2026-07-11 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attendance_options_alter_gym_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('receptionist', 'Receptionist'), ('trainer', 'Trainer')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='core.gym')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__username'],
                'indexes': [models.Index(fields=['gym', 'role'], name='core_staffp_gym_id_da8126_idx'), models.Index(fields=['gym', 'is_active'], name='core_staffp_gym_id_9b3d4f_idx')],
                'constraints': [models.UniqueConstraint(fields=('gym', 'user'), name='unique_staff_user_per_gym')],
            },
        ),
    ]
