# Generated by Django 6.0.7 on 2026-07-12 05:38

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gymsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='member',
            new_name='member_gym_name_idx',
            old_name='core_member_gym_id_456482_idx',
        ),
        migrations.RenameIndex(
            model_name='member',
            new_name='member_gym_phone_idx',
            old_name='core_member_gym_id_e9f0cc_idx',
        ),
        migrations.RenameIndex(
            model_name='member',
            new_name='member_gym_expiry_idx',
            old_name='core_member_gym_id_ff9afa_idx',
        ),
        migrations.RenameIndex(
            model_name='member',
            new_name='member_gym_active_idx',
            old_name='core_member_gym_id_efca5f_idx',
        ),
        migrations.AddField(
            model_name='member',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.member_photo_upload_path),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gym', 'is_deleted'], name='member_gym_deleted_idx'),
        ),
    ]
