# Generated by Django 6.0.7 on 2026-07-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_core_member_gym_id_456482_idx_member_gym_name_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='access_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='access_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
